# 
# Copyright 2021 The KubeSphere authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

name: WorkFlow for Building adapter image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'


env:
  REPO: frezes

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Build Image for adapter
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image for adapter
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/WhizardTelemetry".insteadOf "https://github.com/WhizardTelemetry"     
          tag=$(cat VERSION | tr -d " \t\n\r")
          make docker-build -e REPO=${{ env.REPO }} -e TAG=$tag
          docker push ${{ env.REPO }}/whizard-adapter:$tag